### ISSUE TITLE
Couldn't place file in domain

### ISSUE THREAD

**Issue by macbroadcast** [Gandi/letsencrypt-gandi#11]
Hello,
after installing the certbot with apt-get on ubuntu 16.04 TLS and cloning/installing the repo,
i  got an error after executing the following command:

> letsencrypt run --domains macbroadcast.org \
> --authenticator letsencrypt-gandi:gandi-shs \
> --letsencrypt-gandi:gandi-shs-name wordpress \
> --letsencrypt-gandi:gandi-shs-vhost macbroadcast.org \
> --letsencrypt-gandi:gandi-shs-api-key myAPIkey\
> --installer letsencrypt-gandi:gandi-shs

error message:

`letsencrypt: error: unrecognized arguments: --gandi letsencrypt-gandi:gandi-shs`

I forgot a space behind the API key, after i corrected and use "sudo" i got this error:

> macbroadcast@macbroadcast:~/development/letsencrypt-gandi$ sudo letsencrypt run --domains macbroadcast.org --authenticator letsencrypt-gandi:gandi-shs --letsencrypt-gandi:gandi-shs-name wordpress --letsencrypt-gandi:gandi-shs-vhost macbroadcast.org --letsencrypt-gandi:gandi-shs-api-key myAPIkey --installer letsencrypt-gandi:gandi-shs
> An unexpected error occurred:
> Fault: <Fault 510150: 'Error on object : OBJECT_ACCOUNT (CAUSE_NORIGHT) [Invalid API key]'>
> Please see the logfiles in /var/log/letsencrypt for more details.

ok,it seems i used the wrong API  key, after changing key i got this error:

>  355442@sftp.dc1.gpaas.net's password: 
> Connected to sftp.dc1.gpaas.net.
> sftp> exit
> Permission denied (publickey,password).
> Couldn't read packet: Connection reset by peer
> Permission denied (publickey,password).
> Couldn't read packet: Connection reset by peer
> Permission denied (publickey,password).
> Couldn't read packet: Connection reset by peer
> Couldn't place file in domain: vhosts/macbroadcast.org/htdocs//.well-known/acme-challenge

But i am able to  login without my password, just using keys to:

> macbroadcast@macbroadcast:~$ sftp 355442@sftp.dc1.gpaas.net
> Connected to sftp.dc1.gpaas.net.
> sftp>

**Comment by blueclochard** [comment]
I had exactly the same problem, but fixed it by adding this to /etc/sudoers 

`Defaults env_keep+=SSH_AUTH_SOCK`

And then repeat your last command again with sudo.

**Comment by macbroadcast** [comment]
thanks @blueclochard  ,i get closer :smile:  ,after adding the line to the sudoers file i get this error 

>  macbroadcast@macbroadcast:~$ sudo letsencrypt run --domains macbroadcast.org --authenticator letsencrypt-gandi:gandi-shs --letsencrypt-gandi:gandi-shs-name wordpress --letsencrypt-gandi:gandi-shs-vhost macbroadcast.org --letsencrypt-gandi:gandi-shs-api-key xxxxxxxxxxxxxxxxx --installer letsencrypt-gandi:gandi-shs
> [sudo] Passwort für macbroadcast: 
> Warning: Permanently added the RSA host key for IP address '173.246.99.26' to the list of known hosts.
> Connected to sftp.dc1.gpaas.net.
> sftp> exit
> sftp> -mkdir vhosts/macbroadcast.org/htdocs//
> Couldn't create directory: No such file or directory
> sftp> -mkdir vhosts/macbroadcast.org/htdocs//.well-known/
> Couldn't create directory: No such file or directory
> sftp> -mkdir vhosts/macbroadcast.org/htdocs//.well-known/acme-challenge
> Couldn't create directory: No such file or directory
> sftp> cd vhosts/macbroadcast.org/htdocs//.well-known/acme-challenge
> Couldn't canonicalize: No such file or directory
> sftp> cd vhosts/macbroadcast.org/htdocs//.well-known
> Couldn't canonicalize: No such file or directory
> sftp> rm vhosts/macbroadcast.org/htdocs//.well-known/acme-challenge/xxxxxxxxxxxxxxxxxxxxxxxxx
> Couldn't delete file: No such file or directory
> Couldn't place file in domain: vhosts/macbroadcast.org/htdocs//.well-known/acme-challenge
> macbroadcast@macbroadcast:~$ 

I read on stackoverflow **"With SFTP you can only copy if the directory exists"** but why is there a **mkdir** command ? So i had to manually create the directories ?

**Comment by blueclochard** [comment]
I just had a look at my bash history and I also got similar errors yesterday:

`Couldn't create directory: Failure`

In my case all directories already existed however, and despite the errors letsencrypt was able to successfully place the certificate. The directories already existed because I had used letsencrypt before in manual mode. You could always try creating the directories by hand, though at least the htdocs directory should exist by default I believe.

Are you using the version of letsencrypt that comes with Ubuntu? I remember I had problems with that and ended up using the newest version of letsencrypt which now is called certbot. Just do:

```
git clone https://github.com/certbot/certbot
cd certbot
```

And after that repeat this command you did before, but replace the first letsencrypt with certbot. The letsencrypt-gandi parts remain the same.

`sudo certbot run --domains macbroadcast.org --authenticator letsencrypt-gandi:gandi-shs --letsencrypt-gandi:gandi-shs-name wordpress --letsencrypt-gandi:gandi-shs-vhost macbroadcast.org --letsencrypt-gandi:gandi-shs-api-key xxxxxxxxxxxxxxxxx --installer letsencrypt-gandi:gandi-shs`

And if you copy the above, you of course need to use your own API-key. Hope that gets you somewhere! I know I struggled several hours yesterday to get something so simple to work. But I frankly admit I am a noob when it comes to these things   :sweat_smile:

**Comment by macbroadcast** [comment]
Fixed, you dont believe how obvious the error was , the vhost i created was

>  vhosts/**www**.macbroadcast.org/htdocs/   

and the domain i specified:

>  --domains macbroadcast.org instead of --domains **www**.macbroadcast.org 

in my letsencrypt command. 

Thanks 

:smiley:
